### PR TITLE
Drop `readable-streams` dependency

### PR DESCRIPTION
**Pull request by fregante**
`stream.Duplex` has been available since Node ~~6.8.0~~ _0.9.4_

https://nodejs.org/api/stream.html#duplex-and-transform-streams

### CODE REVIEW

**Comment by mcollina** [comment]
I suspect Duplex was around from 0.10, but that's not the reason why we are using readable-stream here.

The whole point of readable-stream is to normalize the stream dependency a wide array of Node.js versions.

**Comment by mcollina** [comment]
I think this PR should include a bump to a minimum supported version of node v18 (right now it's v14 for this module).

**Comment by fregante** [comment]
I don’t think CI failing is due to a bump, it seems GitHub actions is just failing to download Node. Try again:

> Attempting to download 14...
> Not found in manifest. Falling back to download directly from Node
> Error: Unable to find Node version '14' for platform darwin and architecture arm64.

**Comment by fregante** [comment]
> to normalize the stream dependency a wide array of Node.js versions.

I don’t know much on the topic, but the article linked on `readable-streams` explaining this is exactly 10 years old, I think we’re past the streams 2/3 issues: https://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html

**Comment by jsumners** [comment]
> I don’t think CI failing is due to a bump, it seems GitHub actions is just failing to download Node. Try again:
> 
> > Attempting to download 14...
> > Not found in manifest. Falling back to download directly from Node
> > Error: Unable to find Node version '14' for platform darwin and architecture arm64.

Seems like some sort of bug:

https://github.com/actions/node-versions/blob/75581b602712663c8c992deca984d30c12624e88/versions-manifest.json#L3232

Far easier to just remove 14 from the matrix.

**Review by jsumners — APPROVED** [review]

**Pull request merged**
