### PR TITLE
Update for v9

### PR DESCRIPTION
**Pull request by mohammedbalila**
This PR addresses issue #97 
This package uses `tap` for testing so no work there was needed.
I updated dependencies for the latest version and dropped node `14` and `16` from the CI

But please feel free to let me know if any work is needed. Thanks

@mcollina

### CODE REVIEW

**Comment by jsumners** [comment]
Please see the existing `next` branch. It needs to be rebased on the primary branch.

**Comment by mohammedbalila** [comment]
Hi @jsumners 
I see that the `next` branch already has most of my changes and more, should I close this PR?

**Comment by jsumners** [comment]
Yes. You can see the PR I did a few weeks ago. Changes that have been made since need to be incorporated.

**Comment by mohammedbalila** [comment]
Alright

**Pull request closed without merging**
